sudo: false
language: ruby
cache: bundler
rvm:
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - 2.1.7
 - 2.2.4
 - 2.3.0
 - ruby-head

before_install:
 # stub mplayer/ffmpeg so it looks like they are installed
 - mkdir ~/bin
 - touch ~/bin/mplayer ~/bin/ffmpeg
 - chmod +x ~/bin/mplayer ~/bin/ffmpeg
 - export PATH=~/bin:$PATH
 - git --version

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  except:
    - gh-pages

notifications:
  slack:
    secure: BkGsQOYMJqW55j94S1QwmR17BkwuTIULKVhwzRdnv37BvVcC17y9KLMo8NH+bcao36XZx9DukXcTyaDQc6tCSlFEbG/FcPUJM8bx9EWjHUoGVg1KdpVu/nVHu+GKosrB41lM3nfJWCnF0TOSnmTXU+bV8Pwkij+L5X+gNyAT2Ns=

deploy:
  provider: rubygems
  api_key:
    secure: Y7FFOMDahITtHYRV3UQAw+BA2JbqoArN/Ii9PUTU6RaLmTIvpZBzqtvR3r8ah3SdXNh0Cx10gVf0pRc6HXKTNQdwMWCkOQwukAb+9kLDKFxl3x+w4X2u6yWmtsyNMTWK1gF4hEF1IHnsdg2dYEoFfE2M5bHex85ND/Q6820sPa8=
  gem: lolcommits
  on:
    tags: true
    all_branches: true
    repo: mroth/lolcommits
